### ISSUE TITLE
justsomedood PPA is not working anymore

### ISSUE THREAD

**Issue by sajeshcherian** [quassy/elementary-apps#60] opened 2016-05-12 13:36 UTC
sudo apt-get update gives this error for justsomedood PPA.

W: Failed to fetch http://ppa.launchpad.net/justsomedood/justsomeelementary/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/justsomedood/justsomeelementary/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

A lot of apps for Elementary uses this PPA. If it has gone defunct, please provide some alternatives.

**Comment by inputsh** [comment] 2016-05-12 14:07
Seems like a duplicate of #59.

**Comment by quassy** [comment] 2016-05-13 16:20
Thanks for reporting the issue, I'm afraid many other links and PPA references are outdated as well (ideally I'd have an automated system to check those). I will remove links to justsomeelementary from elementary apps. 

Unfortunately I don't know of any suitable alternative right now, maybe someone else does?

If anyone knows an easy way to automatically check PPAs, that would be nice to know as well.

**Closed as completed** 2016-05-13 16:35 UTC
Labels: bug
